# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='manager', max_length=20),
        ),
    ]
