# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField()),
                ('number', models.PositiveSmallIntegerField()),
                ('type', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('gender', models.TextField(max_length=10)),
                ('student_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='importing.Student'),
        ),
    ]
