# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='number',
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.TextField(),
        ),
    ]
