# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0002_auto_20151210_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='the_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='importing.Class'),
        ),
    ]
