# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0003_auto_20151210_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_in_class',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
