# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0004_student_id_in_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.TextField(max_length=20),
        ),
    ]
