# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0005_auto_20151210_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='date_to_come',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='times_remain_to_clean',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
