# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0007_auto_20151223_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='the_class',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
